# Generated by Django 3.1.14 on 2023-12-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231217_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
